import 'package:flutter/material.dart';

import './api_generated.dart';

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);


  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: TextWords(),
      )
    );
  }
}

class TextWords extends StatefulWidget {
  const TextWords({Key? key}) : super(key: key);

   @override
  State<StatefulWidget> createState() {
    return new TextWordsState();
  }
}

class TextWordsState extends State<TextWords> {
  Future<String?> callNativePlatform() async {
    // `Api` is a class generated by Pigeon
    final api = Api();
    final res = await api.getPlatformVersion();
    // ignore: avoid_print
    print(res.string);
    return res.string;
  }
  String version = '';
  @override
  Widget build(BuildContext context) {
    return Row(
        children: [
        Center(
          child: ElevatedButton(
          child: const Text("call native method"),
          onPressed: () => callNativePlatform().then((value) => setState(() {
             version = value!;
             })),
        )
        ),
        // const Flexible(child: SizedBox(), fit: FlexFit.tight),
        const Padding(padding: EdgeInsets.fromLTRB(20, 0, 0, 0)),
        Align(
              alignment: Alignment.centerRight,
              child: Text(version),
        ),
        ]
      );
  }
}